name_map:
  - ["sa1.mlp_convs.0", Flat()]
  - ["sa1.mlp_bns.0", Pass()]
  - ["sa1.mlp_convs.1", ZPlus()]
  - ["sa1.mlp_bns.1", Pass()]
  - ["sa1.mlp_convs.2", ZPlus()]
  - ["sa1.mlp_bns.2", Pass()]
  - ["sa2.mlp_convs.0", ZPlus()]
  - ["sa2.mlp_bns.0", Pass()]
  - ["sa2.mlp_convs.1", ZPlus()]
  - ["sa2.mlp_bns.1", Pass()]
  - ["sa2.mlp_convs.2", ZPlus()]
  - ["sa2.mlp_bns.2", Pass()]
  - ["sa3.mlp_convs.0", ZPlus()]
  - ["sa3.mlp_bns.0", Pass()]
  - ["sa3.mlp_convs.1", ZPlus()]
  - ["sa3.mlp_bns.1", Pass()]
  - ["sa3.mlp_convs.2", ZPlus()]
  - ["sa3.mlp_bns.2", Pass()]
  - ["fc1", ZPlus()]
  - ["bn1", Pass()]
  - ["drop1", Pass()]
  - ["fc2", ZPlus()]
  - ["bn2", Pass()]
  - ["drop2", Pass()]
  - ["fc3", ZPlus()]

